stopper: data/stoplist.kba
indexRoot: /data0/willis8/indexes
bgStatType: edu.gslis.docscoring.support.IndexBackedCollectionStats
runPrefix: base
outputDir: ./output
numThreads: 20
scorers:
  - name: qdp-of
    className: edu.gslis.scorers.temporal.QDPScorer
    params:
       mu : 500,1000,1500,2000,2500,3000
#       lambda : 0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9
       lambda : 0.1,0.3,0.5,0.7,0.9
collections:
#  - name: latimes-krovetz
#    index: latimes.temporal.krovetz
#    queries:
#      title: ./topics/topics.latimes.301-400.krovetz.indri
#    qrels: ./qrels/qrels.latimes
#    startDate: 599637600
#    endDate: 662688000
#    interval: 86400
#  - name: ap-krovetz
#    index: ap.temporal.krovetz
#    queries:
#      title: ./topics/topics.ap.51-150.krovetz.indri
#    qrels: ./qrels/qrels.ap.51-150
#    startDate: 571647000
#    endDate: 631169940
#    interval: 86400
  - name: tweets2011-krovetz
    index: tweets2011.temporal.krovetz
    queries:
      title: ./topics/topics.microblog2011.krovetz.indri
    qrels: ./qrels/qrels.tweets2011
    startDate: 1295740800
    endDate: 1297209600
    interval: 3200
#  - name: ft-krovetz
#    index: ft.temporal.krovetz
#    queries:
#      title: ./topics/topics.ft.301-400.krovetz.indri
#    qrels: ./qrels/qrels.ft.301-400
#    startDate: 662688000
#    endDate: 788918400
#    interval: 86400
#  - name: blog06
#    index: blog06.temporal
#    queries:
#      title: ./topics/topics.blog06.851-1050.indri
#    qrels: ./qrels/qrels.blog06.851-1050
#    startDate: 1133827200
#    endDate: 1140566400
#    interval: 3600
#  - name: tweets2012-krovetz
#    index: tweets2011.temporal.krovetz
#    queries:
#      title: ./topics/topics.microblog2012.krovetz.indri
#    qrels: ./qrels/qrels.tweets2012
#    startDate: 1295740800
#    endDate: 1297209600
#    interval: 3600
